# Not strictly what one would do, but this test is rigged to run under Bundler.
# So, the Vagrant plugin loader is not available, but we do have access to the
# Bundler environment for the project.
require 'vagrant-auto_network'

# If this test is being run on a host that also uses auto_network in a normal
# Vagrant environment then there will already be network interfaces listening.
# Most likely in the range of 10.20.0.0/16. The following environment variable
# is set per-provider in the vagrant-spec config.
AutoNetwork.default_pool = ENV["AUTO_NETWORK_TEST_RANGE"]

Vagrant.configure('2') do |config|
  config.vm.provider 'virtualbox' do |vb|
    # Clean up network interface after tests.
    vb.destroy_unused_network_interfaces = true
  end

  config.vm.box = 'box'
  config.vm.network 'private_network', :auto_network => true
end
